# Site settings
title: Praqma's Photogallery Generator
tag_text:
description: ...could definitely be automated one day
baseurl: /photogallery
baseurl_web_host: http://code.praqma.com

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["README.md"]
